# Generated by Django 3.1.6 on 2021-02-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20210218_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empregado',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='empregado',
            new_name='cliente',
        ),
    ]
